services:
  web:
    build: .
    container_name: doghotel_web
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: doghotel_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: doghotel_nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/static
      - media_volume:/media
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: doghotel_certbot
    volumes:
      - certbot_www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt

volumes:
  db_data:
  static_volume:
  media_volume:
  certbot_www:
  letsencrypt:
