# Generated by Django 5.1.6 on 2025-08-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
