# Generated by Django 5.1.6 on 2025-08-11 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_room_price_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDaySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.PositiveSmallIntegerField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_slots', to='hotel.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_slots', to='hotel.room')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'date'], name='hotel_roomd_room_id_d124f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('room', 'date', 'slot'), name='unique_room_date_slot')],
            },
        ),
    ]
